// @ts-check

const sidebars = {
  mainSidebar: [
    {
      type: 'doc',
      id: 'home',
      label: '🏠 首頁',
    },
    {
      type: 'category',
      label: '💡教學資源區',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Tutorial',
        },
      ],
    },
    {
      type: 'category',
      label: '🎬 DaVinci Resolve 教學區',
      items: [
        {
          type: 'autogenerated',
          dirName: 'resolve',
        },
      ],
    },
    
    {
      type: 'category',
      label: '🎹 Finale 教學區',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Finale',
        },
      ],
    },
    
    {
      type: 'category',
      label: '🎮 Roblox 遊戲專區',
      items: [
        {
          type: 'autogenerated',
          dirName: 'roblox',
        },
      ],
    },


    {
      type: 'category',
      label: '📱 手機專區',
      items: [
        {
          type: 'autogenerated',
          dirName: 'phone',
        },
      ],
    },
    {
      type: 'category',
      label: '📂 Vibe Coding 實戰工具包',
      items: [
        {
          type: 'autogenerated',
          dirName: 'vibecoding',
        },
      ],
    },
    {
      type: 'category',
      label: '🎥 影片企劃',
      items: [
        {
          type: 'autogenerated',
          dirName: 'video-set',
        },
      ],
    },

    {
      type: 'category',
      label: '🖥️ macOS 應用程式推薦',
      items: [
        {
          type: 'autogenerated',
          dirName: 'macAPPS',
        },
      ],
    },

    {
      type: 'category',
      label: '🌐 架設網站教學',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Docusaurus',
        },
      ],
    },

    {
      type: 'category',
      label: '🎓 快速上手',
      items: [
        {
          type: 'autogenerated',
          dirName: 'Learn',
        },
      ],
    },
    
  ],
};

module.exports = sidebars;
